---
- name: copy over logstash.keystore to local
  connection: local
  delegate_to: localhost
  run_once: true
  become: false
  aws_s3:
    bucket: "{{ elasticsearch_key_bucket }}"
    object: "elasticsearch_keys/logstash.keystore"
    dest: "./tmp/logstash.keystore"
    mode: get
  changed_when: false
  register: aws_s3_keystore
  until: aws_s3_keystore is succeeded
  retries: 10
  delay: 30

- name: Copy key to remote
  copy:
    src: "./tmp/logstash.keystore"
    dest: "/etc/elasticsearch/logstash.keystore"
    owner: "root"
    group: "elasticsearch"
    mode: "0640"
  changed_when: false

- name: remove temp local keystore
  connection: local
  delegate_to: localhost
  run_once: true
  become: false
  file:
    path: ./tmp/logstash.keystore
    state: absent
  changed_when: false
  failed_when: false