---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Create Logstash configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ logstash_config_file }}"
  notify: restart logstash

- name: Copy over Logstash filters.
  copy:
    src: "filters/{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ logstash_filters}}"
  when: logstash_filter is defined
  notify: restart logstash

- name: Create Logstash filters
  template:
    src: "filter.conf.j2"
    dest: "/etc/logstash/conf.d/filter.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart logstash
  when: logstash_filter is defined

## FIXME: This causes overlogging in elastic-stack on Ubuntu 16.04
# - name: Create Logstash configuration file for local syslog.
#   template:
#     src: 02-local-syslog-input.conf.j2
#     dest: /etc/logstash/conf.d/02-local-syslog-input.conf
#     owner: root
#     group: root
#     mode: 0644
#   when: logstash_monitor_local_syslog
#   notify: restart logstash

- name: Warn user if using insecure SSL key pair.
  debug:
    msg: >
      ***SECURITY RISK***: You are currently using the included/default SSL key
      pair. Please generate your own secure key pair if using this playbook for
      any kind of production purposes!
  when: "logstash_ssl_certificate_file.find('-example.crt') != -1"

- name: Ensure Logstash SSL key pair directory exists.
  file:
    path: "{{ logstash_ssl_dir }}"
    state: directory

- name: Copy SSL key and cert for logstash-forwarder.
  copy:
    src: "{{ item }}"
    dest: "{{ logstash_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ logstash_ssl_key_file }}"
    - "{{ logstash_ssl_certificate_file }}"
  notify: restart logstash

- name: define logstash.yml
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
  notify: restart logstash

- name: set logstash JAVA_OPTS
  lineinfile:
    dest: /etc/default/logstash
    regexp: "^LS_JAVA_OPTS="
    line: "LS_JAVA_OPTS=\"{{ logstash_java_opts }}\""
    insertafter: "^#LS_JAVA_OPTS"
    create: yes
  notify: restart logstash
  when: logstash_java_opts is defined

- name: Set JVM heap size
  lineinfile:
    dest: /etc/logstash/jvm.options
    regexp: "-{{ item }}"
    line: "-{{ item }}{{ logstash_heap_size }}"
  when: logstash_heap_size is defined
  with_items:
    - Xms
    - Xmx
  notify:
    - restart logstash

- name: Ensure Logstash is started and enabled on boot.
  service: "name=logstash state=started enabled={{ logstash_enabled_on_boot }}"
